[package]
name = "noir_rsa"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"
version = "0.8.1"

[dependencies]
bignum = {tag = "v0.7.3", git = "https://github.com/noir-lang/noir-bignum"}
sha256 = { tag = "v0.1.4", git = "https://github.com/noir-lang/sha256" }
sha512 = { tag = "master", git = "https://github.com/noir-lang/sha512" }
sha1 = { tag = "v0.1.0-1", git = "https://github.com/zkpassport/sha1" }
