[package]
name = "noir_rsa"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"
version = "0.4.4"

[dependencies]
bignum = {tag = "v0.5.4", git = "https://github.com/noir-lang/noir-bignum"}
sha256 = { tag = "v0.1.1", git = "https://github.com/noir-lang/sha256" }
sha512 = { tag = "master", git = "https://github.com/noir-lang/sha512" }
